import type { Metadata } from "next";
import { Audiowide, VT323 } from "next/font/google";
import "./globals.css";

const bungee = Audiowide({
  variable: "--orbitron",
  weight: "400",
  subsets: ["latin"],
});
const vt323 = VT323({
  variable: "--vt323",
  weight: "400",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "WebDevelopment & Graphical Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bungee.variable} ${vt323.variable}`}>{children}</body>
    </html>
  );
}
